import { brandConfig } from "@/lib/brand";

export default function TermsPage() {
    return (
        <div className="w-full flex flex-col bg-page-bg min-h-screen pb-20">
            <div className="bg-[#1C1C1E] py-12 px-4 md:px-6">
                <div className="max-w-4xl mx-auto">
                    <h1 className="font-sora text-3xl md:text-5xl font-extrabold text-white mb-4">Terms of Service (Draft)</h1>
                    <p className="text-zinc-400">Last updated: October 2026</p>
                </div>
            </div>

            <main className="max-w-4xl mx-auto px-4 md:px-6 py-12">
                <div className="bg-white p-8 md:p-12 rounded-3xl shadow-sm border border-border-soft prose prose-zinc max-w-none">
                    <div className="bg-yellow-50 border-l-4 border-yellow-400 p-4 mb-8">
                        <p className="text-sm text-yellow-800 m-0">
                            <strong>Note:</strong> This is a draft terms of service based on the platform's real behavior. It must be reviewed by legal counsel before a broader public launch.
                        </p>
                    </div>

                    <h3>1. Acceptance of Terms</h3>
                    <p>By creating an account on CareerPilot AI, you agree to these terms. If you disagree with any part of the terms, you may not use our services.</p>

                    <h3>2. Description of Service</h3>
                    <p>CareerPilot AI provides AI-assisted career tools, including resume parsing, ATS scoring estimates, skill gap analysis, and mock interviews. The platform is currently provided "as is" as an academic/portfolio project.</p>

                    <h3>3. AI Limitations and Disclaimer</h3>
                    <p>The feedback, ATS scores, and roadmaps generated by our AI are estimates intended for educational and preparation purposes. They do not guarantee employment, and real-world employer systems may score your resume differently. Always use your own judgment when making career decisions.</p>

                    <h3>4. User Responsibilities</h3>
                    <ul>
                        <li>You are responsible for maintaining the confidentiality of your account credentials.</li>
                        <li>You agree not to upload malicious files (e.g., malware hidden in resumes).</li>
                        <li>You agree not to abuse the platform's rate limits or attempt to access other users' data.</li>
                    </ul>

                    <h3>5. Account Termination</h3>
                    <p>You can terminate your account at any time via the Settings page. We reserve the right to suspend or terminate accounts that violate these terms or abuse the platform's resources.</p>

                    <h3>6. Changes to Terms</h3>
                    <p>We may update these terms as new AI features are introduced. Users will be notified of significant changes.</p>

                    <h3>7. Contact</h3>
                    <p>For questions regarding these terms, contact <a href={"mailto:" + brandConfig.email}>{brandConfig.email}</a>.</p>
                </div>
            </main>
        </div>
    );
}
