"""Add newsletter model

Revision ID: 5bb4aac546b0
Revises: 941596abedd8
Create Date: 2026-10-01 05:56:56.254998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bb4aac546b0'
down_revision: Union[str, None] = '941596abedd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('newsletter_subs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_newsletter_subs_email'), 'newsletter_subs', ['email'], unique=True)
    op.create_index(op.f('ix_newsletter_subs_id'), 'newsletter_subs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_newsletter_subs_id'), table_name='newsletter_subs')
    op.drop_index(op.f('ix_newsletter_subs_email'), table_name='newsletter_subs')
    op.drop_table('newsletter_subs')
    # ### end Alembic commands ###
