"""Add reset token

Revision ID: b2b5bbf1f100
Revises: 84a6d7915236
Create Date: 2026-10-01 06:56:34.671838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2b5bbf1f100'
down_revision: Union[str, None] = '84a6d7915236'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reset_password_token', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reset_password_token')
    # ### end Alembic commands ###
